### ISSUE TITLE
SEGS Forums - Appearance

### ISSUE THREAD

**Issue by EmileFrost** [Segs/Segs.io#47] opened 2019-04-18 22:23 UTC
It would be great to redecorate the SEGS forums (https://forum.segs.io/index.php) to be eyecatching, more user-friendly and in line with the other SEGS branding.

**Comment by broxen** [comment] 2019-04-26 23:43
Marking this as a duplicate of #1 and closing

**Closed as completed by broxen** 2019-04-26 23:43 UTC
Labels: duplicate, enhancement, help wanted, good first issue
